### ISSUE TITLE
Define API response

### ISSUE THREAD

**Issue by cgendreau** [gbif/gbif-data-validator#1]
The purpose of this issue is to define the response from the API.
The latest version of the API response specifications is available [here](https://github.com/gbif/gbif-data-validator/blob/master/doc/api.md).

The examples below are expressed as JSON for readability and do not necessarily represent the final JSON structure of the response.
## Main structure

``` json
{
  "status": "[OK,FAILED]",
  "indexeable": "[FALSE|TRUE]",
  "error": "Invalid file format",
  "issues": [ ]
}
```
- `"status"` : The global status of the validation
- `"indexeable"` : Is the provided resource indexeable by GBIF?
- `"error"` : Contains human readable message in case the provided resource can not be validated.
- `"issues"` : List of all issues found in the provided resource.
## Issue structure

``` json
"issues": [
    {
      "issue": "RECORDED_DATE_MISMATCH",
      "count": 16,
      "sample": [
        {
          "relatedData": {}
        }
      ]
    }
```
### Record structure related issue

``` json
"relatedData": {
   "line:": "1",
   "identifier": "1",
   "identifierTerm" : "dwc:occurrenceId",
   "description": " 85 instead 90 columns"
}
```
### Occurrence Interpretation related issue

``` json
"relatedData": {
  "line:": "1",
  "identifier": "1",
  "identifierTerm" : "dwc:occurrenceId",
  "dwc:month": "1",
  "dwc:day": "26",
  "dwc:year": "1996",
  "dwc:eventDate": "1996-01-26T01:00Z"
}
```

**Comment by timrobertson100** [comment]
Just a suggestion for the first part

```
{
  "exitMode": "[ok,aborted,terminated]",   // aborted on e.g. service down, terminated on e.g. system error
  "fileFormat": "[csv | DwC-A | Excel,..."], // assuming it can be inferred, worth stating what was detected
  "fileReadable": "[true | false]",    // could the file be opened?
  "referentialIntegrityValid":"[true | false],  // optional
  "uniquenessConstraintsValid":"[true | false],  // optional
  "indexable": "[true | false]",
  "errorMessage": "Indexing of dwc:Event in GBIF requires unique dwc:eventID on the core table",
  "issues": [ ... ]
}
```

Given we're moving towards internationalisation of services, it might be wise to consider in this response.  Things like an `errorCode` could easily handle the translation of an error message, but the `85 instead 90 columns` is harder.  `checkCode`, `expected`, `found` might cover a lot.

It appears worthwhile making a decision on whether we aim to support a translatable UI early in the design.

**Comment by cgendreau** [comment]
`referentialIntegrityValid` and `referentialIntegrityValid` results will be provided in the `issues` block.
Example added to the [API specs document](https://github.com/gbif/gbif-data-validator/blob/master/doc/api.md).
