### ISSUE TITLE
Check that names from well know source are filled in properly for occurrence

### ISSUE THREAD

**Issue by kbraak** [gbif/gbif-data-validator#17]
If the Taxon is defined according to a well known source, it is recommended filling in nameAccordingTo with the name of the source and nameAccordingToID with the identifier for the Taxon assigned as per the source (same as taxonID). 

As per following [recommendation](https://github.com/gbif/ipt/wiki/dataQualityChecklist#if-it-was-a-species-occurrence-related-event---what-species-was-it) in consultation with @mdoering

**Comment by mdoering** [comment]
nameAccordingToID is the identifier for the content of nameAccordingTo, i.e. the source itself not the taxon within that source. It would be very wrong to issue different nameAccordingToIDs for different taxa all coming from the same source. The idea of nameAccordingTo is to represent the taxon concept reference often given as "sensu X" or "sec X", see http://archive.bgbm.org/BioDivInf/Docs/PotentialTaxa/PotentialTaxa.pdf
