### ISSUE TITLE
Decide on internationalisation support

### ISSUE THREAD

**Issue by timrobertson100** [gbif/gbif-data-validator#2]
The user interfaces to the forthcoming GBIF.org are translatable.  Many content items (guidelines etc) are also in various languages.  The IPT is translatable, and we expect to embed this as an option in the IPT.  

Before proceeding too far on the architecture design, a decision should be made on whether the validator needs to support multilingual user interfaces.  Note: This is really for the interface to report issues, not to provide validation of content in various languages.  E.g. it would allow for the interface to translate these statements:
- "37 records missing coordinates"
- "Unknown geodeticDatum received: EPSG 4326"
- "Expected 87 columns.  Received 23"

See https://github.com/gbif/gbif-data-validator/issues/1 for example response.

Getting the highest quality of data into GBIF is of utmost importance.  Making the validator tool as accessible as possible to people with limited English seems like something to strive for.  I therefore think it likely this is a requirement, but this is open for discussion and opinion.

**Comment by cgendreau** [comment]
The current structure would allow to translate the first 2 statements without problem since they can be built from the `issue` block. The last statement requires to change the structure of the COLUMN_COUNT_MISMATCH response which we should do.

Would you rule out the option to receive a language parameter directly in the API request?

**Comment by timrobertson100** [comment]
Not at all.  I had not considered the idea to do all translation within the
API project and support a `&language=DK` rather than returning codes and
letting others do it.  That makes good sense to me.

On Sun, Oct 9, 2016 at 5:09 PM, Christian Gendreau <notifications@github.com

**Comment by timrobertson100** [comment]
Not at all.  I had not considered the idea to do all translation within the API project and support a `&language=DK` rather than returning codes and letting others do it.  That makes good sense to me.

**Comment by MattBlissett** [comment]
HTTP `Accept-Language: da` is the standard way to do that.

But doesn't either way fail to separate the user interface and API?

**Comment by cgendreau** [comment]
I would only consider it for human readable message inside the response but I agree we should probably try to avoid it (there is no need for it at the moment).

If the API would accept a language header, I think it may be easier to format messages with multiple arguments and/or provide a sensible message to users of the API that are using it directly (without the GBIF UI) without having to map a language file.

For the moment, I would target to avoid all translations inside the API and provide keys and arguments in the response.

**Comment by cgendreau** [comment]
keys are used to identify issues making almost all statements translatable.
As today, the only part that can not be translated are details coming from XSD/XML validations.
