### ISSUE TITLE
Safeguard actors running time

### ISSUE THREAD

**Issue by cgendreau** [gbif/gbif-data-validator#20]
It would be useful to have a safeguard that would limit the time an Akka actor can run.
The goal would be to avoid a blocked actor to live "forever" but since we don't have a concrete example of how the code running in actors could block indefinitely, we will keep this as an idea.

**Comment by MattBlissett** [comment]
This project will soon be archived, and replaced by a module in [Pipelines](https://github.org/gbif/pipelines).
