### ISSUE TITLE
Could not find artifact org.gbif:gbif-api:jar:0.52-SNAPSHOT

### ISSUE THREAD

**Issue by meliezer** [gbif/gbif-data-validator#27]
Hello,
I've just tried building (mvn clean package) for the first time:

> [ERROR] Failed to execute goal on project validator-processor: Could not resolve dependencies for project org.gbif.validator:validator-processor:jar:0.1-SNAPSHOT: The following artifacts could not be resolved: org.gbif:gbif-api:jar:0.52-SNAPSHOT, org.gbif:dwc-api:jar:1.17-SNAPSHOT, org.gbif.occurrence:occurrence-processor:jar:0.63-SNAPSHOT, org.gbif.occurrence:occurrence-common:jar:0.63-SNAPSHOT, org.gbif:gbif-common-ws:jar:0.38-SNAPSHOT, org.gbif:dwca-io:jar:1.30-SNAPSHOT, org.gbif.registry:registry-metadata:jar:2.64-SNAPSHOT: Could not find artifact org.gbif:gbif-api:jar:0.52-SNAPSHOT

--
Menashè

**Comment by timrobertson100** [comment]
Hi Menashè

Thanks for raising this.  the 0.52-SNAPSHOT jar is seemingly missing:
  http://repository.gbif.org/content/groups/gbif/org/gbif/gbif-api/0.52-SNAPSHOT/

Can you please change the pom to reference the release and see if that helps?
  http://repository.gbif.org/content/groups/gbif/org/gbif/gbif-api/0.52/

**Comment by meliezer** [comment]
Hi Tim,
No change after adding
    <repository>
      <id>gbif-new</id>
      <url>http://repository.gbif.org/content/groups/gbif/org/gbif/gbif-api/0.52/</url>
    </repository>

**Comment by cgendreau** [comment]
The dependencies version updated (except clb): https://github.com/gbif/gbif-data-validator/commit/03f915aca19cfd031e2b0ca79aa1bf416b546716

Please note this project is not yet released.

**Comment by meliezer** [comment]
Thanks. Compilation error:

> gbif-data-validator/validator-processor/src/main/java/org/gbif/validation/evaluator/record/OccurrenceInterpretationEvaluator.java:[77,54] method interpret in class org.gbif.occurrence.processor.interpreting.OccurrenceInterpreter cannot be applied to given types;
> [ERROR] required: org.gbif.api.model.occurrence.VerbatimOccurrence,org.gbif.api.model.occurrence.Occurrence
> [ERROR] found: org.gbif.api.model.occurrence.VerbatimOccurrence
> [ERROR] reason: actual and formal argument lists differ in length

If you want, I can wait for the release.

**Comment by cgendreau** [comment]
no it should always compile and tests should pass (there is still 1 with intermittent issue).
I skipped one version of the occurrence dependency that's what was causing the issue.

Fixed now

**Comment by meliezer** [comment]
> gbif-data-validator/validator-ws/src/main/java/org/gbif/validation/ws/resources/EnumerationResource.java:[43,46] incompatible types: inference variable U has incompatible bounds
    equality constraints: java.lang.Enum<?>[]
    lower bounds: ? extends java.lang.Enum<?>[]

**Comment by cgendreau** [comment]
at compile time?
I just tried it locally and it compiles correctly (same on the CI server http://builds.gbif.org/job/data-validator/388/)

**Comment by meliezer** [comment]
After successful tests.

> Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project validator-ws: Compilation failure
