### ISSUE TITLE
XMLSchemaValidationProvider relies on internal JDK API being removed in Java-9

### ISSUE THREAD

**Issue by ansell** [gbif/gbif-data-validator#29]
XMLSchemaValidationProvider relies on the internal JDK XML Catalog implementation, com.sun.org.apache.xerces.internal.util.XMLCatalogResolver

This is being removed in Java 9, with an official API replacing it:

http://openjdk.java.net/jeps/268

https://bugs.openjdk.java.net/browse/JDK-8023732

**Comment by MattBlissett** [comment]
This project will soon be archived, and replaced by a module in [Pipelines](https://github.org/gbif/pipelines).
