### ISSUE TITLE
Recursive dependency on the JDK tools.jar which is removed in Java 9

### ISSUE THREAD

**Issue by ansell** [gbif/gbif-data-validator#30]
The dependency on ``org.apache.odftoolkit:simple-odf`` recursively pulls in the ``com.sun:tools:1.7.0:jar`` dependency, through ``odfdom-java`` -> ``taglets``. Tools.jar will not longer exist in Java 9, so this functionality needs to be replaced:

http://openjdk.java.net/jeps/220

Bumping the simple-odf version from ``0.8.1-incubating`` to ``0.8.2-incubating`` does not fix the issue, but may still be useful from a maintenance point of view

Excluding the dependency doesn't seem to have an effect on compile or testing when running under Java-8 (as tools.jar may already be on the classpath anyway).

**Comment by MattBlissett** [comment]
This project will soon be archived, and replaced by a module in [Pipelines](https://github.org/gbif/pipelines).
