### ISSUE TITLE
Duplicate fileName in results while job is running

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/gbif-data-validator#38]
With this input data: https://drive.google.com/uc?export=download&id=0B-BbRNUB6S7aRG9GZzM5MmJhVzQ

The file meta.xml is represented twice in the results with different issues. When the job is finished, theres only one file in the results as expected

`{
"status":"RUNNING","jobId":1505252500092,"result": {"fileName":"nsr.zip","receivedMediaType":"application/zip","fileFormat":"DWCA","validationProfile":"GBIF_INDEXING_PROFILE",
"results":
[
{"fileName":"meta.xml","issues":[{"issue":"UNKNOWN_TERM","relatedData":"http://rs.tdwg.org/dwc/terms/occurrenceStatus","issueCategory":"RESOURCE_STRUCTURE"}],"fileType":"META_DESCRIPTOR","rowType":"http://rs.tdwg.org/dwc/terms/Taxon"},
{"fileName":"meta.xml","issues":[{"issue":"UNKNOWN_TERM","relatedData":"http://data.biodiversitydata.nl/terms/isPreferredName","issueCategory":"RESOURCE_STRUCTURE"},{"issue":"UNKNOWN_TERM","relatedData":"http://rs.tdwg.org/dwc/terms/taxonID","issueCategory":"RESOURCE_STRUCTURE"}],"fileType":"META_DESCRIPTOR","rowType":"http://rs.gbif.org/terms/1.0/VernacularName"}]}}`

**Comment by cgendreau** [comment]
yes, the merge is applied at the end at the moment.

**Comment by thomasstjerne** [comment]
Tested and working as expected now
