### ISSUE TITLE
Generate a map view

### ISSUE THREAD

**Issue by timrobertson100** [gbif/gbif-data-validator#43]
It would be a useful feature to be able to visualise the geographic extent of a dataset on a map.
Showing the map to someone familiar with the underlying data is often the easiest way for them to determine if the geographic coordinates are showing as expected or if there are problems in the dataset.

It may be worth considering both the raw and interpreted coordinates although the raw view makes most sense as it will encourage users to act on issues.

**Comment by MattBlissett** [comment]
If we target OpenLayers in the UI, then there are several options for how to provide the data (MVT, raster, GeoJSON).  If it’s just to show that the data is in the right place, then perhaps 1° cells coloured by frequency would be fine, and GeoJSON should have no problem — then it’s just one API call for the whole map.

That would look roughly like this: http://mb.gbif.org/OpenLayers/4326/small-squares.html#4fa7b334-ce0d-4e88-aaae-2e0c138d049e (eBird), http://mb.gbif.org/OpenLayers/4326/small-squares.html#cd6e21c8-9e8a-493a-8a76-fbf7862069e5 (Kew), http://mb.gbif.org/OpenLayers/4326/small-squares.html#4f70108a-dda7-4e8b-8298-babaee5182c3 (Artportalen).

(This is done with the two vector tiles from zoom 0, squareSize=16, giving 0.7º cells. GeoJSON performance is probably similar.)

If we target Leaflet, we have more options with higher density data, but generating vector tiles seems like a hassle for this.

Either way, I think we should show the raw coordinates, but use a different colour for the cell if there are any that have issues.
