### ISSUE TITLE
Term Frequency as ordered array instead of map

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/gbif-data-validator#47]
Return Term Frequency as array instead of map and order it according to column ordering in the uploaded data file.

**Comment by cgendreau** [comment]
The order should be respected but I'm not sure I follow the part array vs map.
```
"termsFrequency":{"http://unknown.org/ARCHIVE_RECORD_ID":10, "dwc:decimalLatitude":10}
```
looks fine to me.

Do you mean something like:
```
"termsFrequency":[{"http://unknown.org/ARCHIVE_RECORD_ID":10}, {"dwc:decimalLatitude":10}]
```
or an associative array?
```
"headers": ["http://unknown.org/ARCHIVE_RECORD_ID", "dwc:decimalLatitude"]
"termsFrequency":[10,10]
```

**Comment by timrobertson100** [comment]
I presume either of the second or third option are suitable.  The problem with the first is there no guarantee in order depending on how it is deserialized even if it is printed in correct order.  I'd propose the second option is the easiest to digest.

**Comment by thomasstjerne** [comment]
Yes, the second option was what I was after. 
Could be kept as a map if the order was included (But I prefer the array ):
`"termsFrequency":
{
"http://unknown.org/ARCHIVE_RECORD_ID": {"count":10, "order": 0}, 
"dwc:decimalLatitude":  {"count":10, "order": 1}
}`

**Comment by cgendreau** [comment]
ready for the UI
