### ISSUE TITLE
A dataset with no core id is stated as indexable

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/gbif-data-validator#50]
I don´t know if this may be intended.
However, I found this issue https://github.com/gbif/portal-feedback/issues/540 with some occ datasets with 0 occurences, for example this one:
https://www.gbif.org/dataset/929d10ff-6f80-4ab3-a422-509c6721d402

A test in the validator showed that the id column is empty, and I assume this is the reason for the zero occurrences.

**Comment by cgendreau** [comment]
Fixed in the sense it will not be stated as indexable anymore.
But, an empty identifier should not be valid. Currently if it appears only once it will be considered valid.
