### ISSUE TITLE
records missing

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/gbif-data-validator#54]
Not sure if it's premature to report specific observations around the validator, but here goes:

I tried validating a big dataset:
https://www.gbif-dev.org/tools/data-validator/1508317119771
DwC-A: https://ipt.gbif.org/archive.do?r=rainbio&v=1.1

It was done very quickly, but the number of records in the validation report  (~99k) is less than the number of records in the DwC-A (~600k).

**Comment by cgendreau** [comment]
If I upload the file, it seems to work: https://www.gbif-dev.org/tools/data-validator/1508768007575
If I use the URL to let the validator download the file I get the same issue as described in this issue.

**Comment by cgendreau** [comment]
File upload fixed via resolution of Issue #55
