### ISSUE TITLE
Validation of GBIF.org source DwC-A says not indexable

### ISSUE THREAD

**Issue by timrobertson100** [gbif/gbif-data-validator#57]
I used a [dwca downloaded from GBIF.org](https://github.com/gbif/gbif-data-validator/files/1412160/dwca-lep2.zip) downloaded from GBIF which produced [this report](https://www.gbif.org/tools/data-validator/1508848348028).

It is unexpected to see unknown terms, license not parseable, resource creator, basisOfRecord issues and geodeticDatum issues.  Taxon matching to higher rank seems understandable.

I would expect GBIF.org sourced data to validate but we flag otherwise.  It could be that this needs transferred to issues in another project of course.

**Comment by cgendreau** [comment]
- Unknown terms are expected since they are not part of the definition of Occurrence "class" in Darwin Core
- License and Creator are indeed unexpected (but should be fixed in the code that produce the archive)
- basisOfRecord and geodeticDatum are on the verbatim extension, this is also expected.

**Comment by timrobertson100** [comment]
I'm not sure I agree. Wouldn't most users expect the GBIF validator to know all terms produced in a GBIF.org created archive?

**Comment by cgendreau** [comment]
Probably but we don't have a class for that (interpreted records) and we re-use the Occurrence class (aka rowType). As far as I know there is no formal definition of what is included in the download archive to validate against.

Note: Unknown terms means Unknown terms in the context of the rowType.
