### ISSUE TITLE
verbatim coordinates should not be stated as "coordinate invalid"

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/gbif-data-validator#63]
The report is for invalid verbatimCoordinates. It is not possible to have invalid verbatim data. It is possible to not be able to interpret it automatically, but the fault is as easily on the one trying to interpret it as it is on the source. Case in point: "14d 49m s S/70d 1m s W". That is easily interpretable. Nothing wrong with it. Certainly not invalid.

Maybe flag as "not interpretable by gbif" and severity =INFO when it is verbatim data  ?

See: https://github.com/gbif/portal-feedback/issues/607
And https://www.gbif.org/tools/data-validator/1508848348057

**Comment by MattBlissett** [comment]
This is not an issue with the validator, as it's following the normal GBIF interpretation.

Closing in favour of https://github.com/gbif/occurrence/issues/83
