### ISSUE TITLE
Providing url for archive gives 503

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/gbif-data-validator#65]
Archive size app 70 mb

https://api.gbif.org/v1/validator/jobserver/submiturl?fileUrl=https:%2F%2Fcollections.nmnh.si.edu%2Fipt%2Farchive.do%3Fr%3Dnmnh_paleo_dwc-a%26v%3D1.10

**Comment by MattBlissett** [comment]
Hmm, do we want to be able to submit archives in this way? Every time Google etc follows this link, a validation will be triggered. (Unless there's some auth I'm missing.)

**Comment by thomasstjerne** [comment]
The API should require Auth: https://github.com/gbif/gbif-data-validator/issues/49
Just not implemented yet

**Comment by MattBlissett** [comment]
This project will soon be archived, and replaced by a module in [Pipelines](https://github.org/gbif/pipelines).
