### ISSUE TITLE
Support xlsx spreadheets?

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/gbif-data-validator#67]
See: https://github.com/gbif/portal-feedback/issues/1233

**Comment by cgendreau** [comment]
It should already be supported.
https://github.com/gbif/gbif-data-validator/blob/master/validator-processor/src/test/java/org/gbif/validation/source/ExcelConverterTest.java#L20

**Comment by cgendreau** [comment]
And `Occurrences` should be recognized as the sheet to convert https://github.com/gbif/gbif-data-validator/blob/master/validator-processor/src/main/java/org/gbif/validation/source/DataFileFactory.java#L57

**Comment by thomasstjerne** [comment]
Api responds with 415 Unsupported file type: application/x-tika-ooxml

**Comment by cgendreau** [comment]
ok, that's different.
[MediaTypeAndFormatDetector](https://github.com/gbif/gbif-data-validator/blob/master/validator-processor/src/main/java/org/gbif/detect/MediaTypeAndFormatDetector.java) is responsible for that but `application/x-tika-ooxml` looks wrong (the `tika` part).

**Comment by cgendreau** [comment]
It is expected based on Tika tests: https://github.com/apache/tika/blob/master/tika-parsers/src/test/java/org/apache/tika/mime/TestMimeTypes.java#L276
We may want to check if we could use a `TikaInputStream`  instead in `MediaTypeAndFormatDetector`.

**Comment by cgendreau** [comment]
So the issue is that from an `InputStream` alone `application/x-tika-ooxml` may be the best Tika can detect. If we provide a filename it will be able to refine it (sent as Pull Request).
See "The default Mime Types Detector" on https://tika.apache.org/1.1/detection.html
