### ISSUE TITLE
validation.issueType.OCCURRENCE_NOT_UNIQUELY_IDENTIFIED with 1 record

### ISSUE THREAD

**Issue by gbif-portal** [gbif/gbif-data-validator#81]
**validation.issueType.OCCURRENCE_NOT_UNIQUELY_IDENTIFIED with 1 record**

The Archive tested is this one:
[test.zip](https://github.com/gbif/portal-feedback/files/3007448/test.zip)

-----

User provided contact info: @ManonGros
System: Safari 12.0.3 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/a086dc637709189cecd8443018c1f8ad:9faab8f42b0e8b2304f990404b185363b395e7dc8d99d1db64fe3b4516b3b114b6f4c6d1ee748248bc7383c6d728e865aa25b77fd6eca4c764eba52ab0374072)
Referer: https://www.gbif.org/tools/data-validator/1546511790532
Window size: width 1615 - height 888
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-26T09:33:42.765Z',mode:absolute,to:'2019-03-26T09:39:42.765Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-26T09:33:42.765Z',mode:absolute,to:'2019-03-26T09:39:42.765Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
Strangely the micro archive that Marie put up does validate IF the occurrence.txt header line is removed and the meta.xml has ignoreHeaderLines=0

https://www.gbif.org/tools/data-validator/1546511790537

**Comment by MattBlissett** [comment]
There is a race condition.

Because the file is so small, and because both uniqueness tests (coreId and occurrenceId) are run in parallel, they clash and the temporary file ends up with duplicated contents.

**Comment by MattBlissett** [comment]
With no header line, the sorted contents overwrites (rather than appends to) the temporary file, so the issue doesn't appear -- well spotted.

**Comment by ManonGros** [comment]
But the original problem came from a bigger file (I just extracted the line with the issue), what does it mean? Original validation: https://www.gbif.org/tools/data-validator/1546511790434

**Comment by ManonGros** [comment]
From @jeroencreuwels:
> If I remove the record that gives problems from the dataset, and validate the new dataset in the validator a new record with integrity issues pops up. Sometimes in Occurrence.txt, sometimes in Multimedia.txt. Each time the records are unique, and somehow recordId and occurrenceID are not correct and consecutive number as is shown below. This gives me the feeling that there is something wrong in the datavalidator.
 
> *First validator report*: 
https://www.gbif.org/tools/data-validator/1546511790434
 `validation.issueType.OCCURRENCE_NOT_UNIQUELY_IDENTIFIED`
WAG.1920591@BRAHMS and  WAG.1920590@BRAHMS give problems.

> *Second validator report*:   
https://www.gbif.org/tools/data-validator/1546511790487
After removing two records in Occurrence.txt, there are problems with multimedia.txt (same record numbers), not with occurrence.txt.
 
![Unknown](https://user-images.githubusercontent.com/7677271/55000859-b3845a00-4fd3-11e9-8e4f-4d2ea5906b3b.png)

> *Third validator report*:     
https://www.gbif.org/tools/data-validator/1546511790491
After removing the two records above in Multimedia.txt, there are problems with multimedia, not with occurrences  

![Unknown-1](https://user-images.githubusercontent.com/7677271/55000867-b7b07780-4fd3-11e9-901d-85e40c66774e.png)

> https://www.gbif.org/tools/data-validator/1546511790492
After removing the record above in Occurrence.txt, there is another problem with Occurrence.txt  

![Unknown-2](https://user-images.githubusercontent.com/7677271/55000974-ee868d80-4fd3-11e9-83e1-f73d938bd6ee.png)
