### ISSUE TITLE
Enhance metadata validation

### ISSUE THREAD

**Issue by cgendreau** [gbif/gbif-data-validator#9]
- [x] Parse EML as a Dataset object
- [x] Ensure license can be parsed
- [x] Ensure there is a description 
- [x] Ensure there is a creator and a contact

**Comment by kbraak** [comment]
To help understand what metadata terms GBIF requires and recommends as well as what quality checks are performed on these metadata fields please refer to the following resources: 
* [Required metadata fields](https://github.com/gbif/ipt/wiki/resourceMetadata#required-metadata-fields)
* [Recommended metadata fields](https://github.com/gbif/ipt/wiki/resourceMetadata#recommended-metadata-fields)
* [Metadata field quality checks](https://github.com/gbif/ipt/wiki/dataQualityChecklist#dataset-metadata)

**Comment by dschigel** [comment]
Can it be expanded a bit, so creator s etc are not only NOT_EMPTY but also formated so there is last name and at least one initial?
